project_root: .
singlevla_pretrained_path: external/TwinVLA-base
data_root_dir: external/aloha_rlds
data_mix: aloha_handover_box
max_steps: 40000
save_at_steps: [10000, 20000, 30000, 40000]
learning_rate: 0.0002
weight_decay: 0.00001
adam_beta1: 0.9
adam_beta2: 0.999
adam_eps: 0.00000001
warmup_ratio: 0.01
lr_scheduler_type: cosine
max_grad_norm: 1.0
shuffle_buffer_size: 50000
num_workers: 16
num_parallel_calls: 16
log_steps: 100
seed: 2601
bf16: true
freeze_vision_backbone: true
no_freeze_llm_backbone: true
no_ddp_find_unused_parameters: true
decoder_mode: separate_decoders
loss_reduction: sum
common_strategy: local_common
common_fusion_mode: fixed_avg
remote_kv_scale: 1.0
remote_kv_dropout_prob: 0.0
